# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i -g yarn
    - run: yarn
    - run: yarn bundle
    - uses: thezzisu/git-repo-deploy-action@v1.0.2
      with:
        repo: ${{ secrets.REPO_WITH_TOKEN }}
        name: thezzisu
        email: thezzisu@gmail.com
        branch: latest
